"""add_box_services_table

Revision ID: 717fae593cf9
Revises: a8f8fd3fced2
Create Date: 2026-07-25 16:19:03.691053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '717fae593cf9'
down_revision: Union[str, Sequence[str], None] = 'a8f8fd3fced2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('box_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('box_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['box_id'], ['boxes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_box_services_box_id'), 'box_services', ['box_id'], unique=False)
    op.create_index(op.f('ix_box_services_id'), 'box_services', ['id'], unique=False)
    op.create_index(op.f('ix_box_services_service_id'), 'box_services', ['service_id'], unique=False)
    op.create_index(op.f('ix_box_services_tenant_id'), 'box_services', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_box_services_tenant_id'), table_name='box_services')
    op.drop_index(op.f('ix_box_services_service_id'), table_name='box_services')
    op.drop_index(op.f('ix_box_services_id'), table_name='box_services')
    op.drop_index(op.f('ix_box_services_box_id'), table_name='box_services')
    op.drop_table('box_services')
    # ### end Alembic commands ###
