"""add box_id to appointments

Revision ID: a8f8fd3fced2
Revises: beb4da092f28
Create Date: 2026-07-25 14:28:58.310509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8f8fd3fced2'
down_revision: Union[str, Sequence[str], None] = 'beb4da092f28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Название бокса'),
    sa.Column('color', sa.String(length=20), nullable=True, comment='Цвет для UI (hex)'),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boxes_id'), 'boxes', ['id'], unique=False)
    op.create_index(op.f('ix_boxes_tenant_id'), 'boxes', ['tenant_id'], unique=False)
    op.add_column('appointments', sa.Column('box_id', sa.Integer(), nullable=True, comment='Бокс/зона выполнения'))
    op.create_index(op.f('ix_appointments_box_id'), 'appointments', ['box_id'], unique=False)
    op.create_foreign_key(None, 'appointments', 'boxes', ['box_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_client_discounts_id'), 'client_discounts', ['id'], unique=False)
    op.alter_column('discount_rules', 'type',
               existing_type=sa.VARCHAR(length=50),
               comment='happy_hours, frequency, win_back, cashback, service, client',
               existing_comment='happy_hours, frequency, win_back, cashback',
               existing_nullable=False)
    op.create_index(op.f('ix_discount_rules_id'), 'discount_rules', ['id'], unique=False)
    op.alter_column('expenses', 'category',
               existing_type=sa.VARCHAR(length=50),
               comment='rent, salary, utilities, marketing, supplies, other',
               existing_nullable=False,
               existing_server_default=sa.text("'other'::character varying"))
    op.add_column('loyalty_points', sa.Column('tier', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_loyalty_points_id'), 'loyalty_points', ['id'], unique=False)
    op.drop_constraint(op.f('users_phone_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_phone_key'), 'users', ['phone'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_loyalty_points_id'), table_name='loyalty_points')
    op.drop_column('loyalty_points', 'tier')
    op.alter_column('expenses', 'category',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='rent, salary, utilities, marketing, supplies, other',
               existing_nullable=False,
               existing_server_default=sa.text("'other'::character varying"))
    op.drop_index(op.f('ix_discount_rules_id'), table_name='discount_rules')
    op.alter_column('discount_rules', 'type',
               existing_type=sa.VARCHAR(length=50),
               comment='happy_hours, frequency, win_back, cashback',
               existing_comment='happy_hours, frequency, win_back, cashback, service, client',
               existing_nullable=False)
    op.drop_index(op.f('ix_client_discounts_id'), table_name='client_discounts')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_index(op.f('ix_appointments_box_id'), table_name='appointments')
    op.drop_column('appointments', 'box_id')
    op.drop_index(op.f('ix_boxes_tenant_id'), table_name='boxes')
    op.drop_index(op.f('ix_boxes_id'), table_name='boxes')
    op.drop_table('boxes')
    # ### end Alembic commands ###
