"""Compatibility barrel: schemas живут в app.modules.<name>/schemas.py."""
from __future__ import annotations

from app.modules.core.schemas import PaginatedResponse, TenantCreate, TenantUpdate, TenantOut, RegisterRequest, LoginRequest, UserOut, AuthResponse, UserProfileUpdate, UserListOut, UserRoleUpdate, UserDetailOut, RfmClient, SegmentCount, RfmResponse
from app.modules.services.schemas import ServiceCreate, ServiceUpdate, ServiceOut
from app.modules.cars.schemas import CarCreate, CarOut, CarUpdate
from app.modules.appointments.schemas import AppointmentCreate, AppointmentStatusUpdate, MasterStatusUpdate, ClientAppointmentEdit, MasterNotesUpdate, ClientRef, MasterRef, CarRef, ServiceRef, AppointmentOut, BoxCreate, BoxUpdate, BoxOut, BoxServiceOut, WorkingHoursOut, WorkingHoursUpdate, CalendarAppointment, CalendarDay, CalendarResponse, HistoryEntryOut, HistoryResponse
from app.modules.analytics.schemas import KpiOut, RevenuePoint, RevenueResponse, HeatmapCell, HeatmapResponse, FunnelStage, FunnelResponse, ServiceTrendPoint, ServiceTrend, ServiceComparison, TopService, ForecastPoint, ServiceAnalyticsResponse, RevenueDetail, PeriodComparison, MasterRevenueSummary, ServiceRevenueSummary, RevenueReportResponse
from app.modules.ai.schemas import ChatRequest, ChatResponse, FinancierRequest, FinancierResponse
from app.modules.expenses.schemas import ExpenseCreate, ExpenseUpdate, ExpenseOut, ExpenseCategoryItem, ExpenseCategoryBreakdown, ExpenseMonthPoint, ExpenseInsight, ExpenseAnalyticsResponse, ServiceMargin, PLReport
from app.modules.discounts.schemas import DiscountRuleCreate, DiscountRuleUpdate, DiscountRuleOut, ClientDiscountOut, DiscountAnalyticsTopRule, DiscountAnalyticsResponse, DiscountSuggestion, DiscountRuleAdvice, DiscountRoiItem, DiscountBeforeAfterPoint, DiscountIntelligenceResponse, ServiceDiscountRecOut, ServiceDiscountRecDecision, ServiceDiscountRecAnalyticsPoint, ServiceDiscountRecsResponse, LoyaltyPointsOut, LoyaltyPointsSummary, LoyaltyTierConfigOut, LoyaltyTierConfigUpdate, ClientTierOut
from app.modules.photos.schemas import PhotoOut, PhotoOrderUpdate, PhotoCreateResponse
from app.modules.notifications.schemas import NotificationOut, UnreadCountOut, NotificationSettingsOut, NotificationSettingsUpdate, TelegramConnectRequest
from app.modules.payments.schemas import PaymentCreateRequest, PaymentOut, PaymentWebhookRequest
from app.modules.materials.schemas import MATERIAL_CATEGORIES, MATERIAL_UNITS, MaterialCreate, MaterialUpdate, MaterialOut, MaterialCategoryItem
from app.modules.inventory.schemas import MaterialMovementOut, StockHistoryPoint, AbcItemOut, CriticalItemOut, InventorySummaryOut
from app.modules.tech_cards.schemas import TechCardItemIn, TechCardItemOut, TechCardBlockIn, TechCardBlockOut, TechCardCreate, TechCardUpdate, TechCardOut, TechCardReorderIn, TechCardPhotoOut
from app.modules.tech_analytics.schemas import PurchaseRecommendOut, AuditServiceBreakout, ConsumptionAuditOut, TechAnalyticsSummaryOut, AnomalyOut, AuditLogOut, AuditSyncResultOut

__all__ = ['PaginatedResponse', 'TenantCreate', 'TenantUpdate', 'TenantOut', 'RegisterRequest', 'LoginRequest', 'UserOut', 'AuthResponse', 'UserProfileUpdate', 'UserListOut', 'UserRoleUpdate', 'UserDetailOut', 'RfmClient', 'SegmentCount', 'RfmResponse', 'ServiceCreate', 'ServiceUpdate', 'ServiceOut', 'CarCreate', 'CarOut', 'CarUpdate', 'AppointmentCreate', 'AppointmentStatusUpdate', 'MasterStatusUpdate', 'ClientAppointmentEdit', 'MasterNotesUpdate', 'ClientRef', 'MasterRef', 'CarRef', 'ServiceRef', 'AppointmentOut', 'BoxCreate', 'BoxUpdate', 'BoxOut', 'BoxServiceOut', 'WorkingHoursOut', 'WorkingHoursUpdate', 'CalendarAppointment', 'CalendarDay', 'CalendarResponse', 'HistoryEntryOut', 'HistoryResponse', 'KpiOut', 'RevenuePoint', 'RevenueResponse', 'HeatmapCell', 'HeatmapResponse', 'FunnelStage', 'FunnelResponse', 'ServiceTrendPoint', 'ServiceTrend', 'ServiceComparison', 'TopService', 'ForecastPoint', 'ServiceAnalyticsResponse', 'RevenueDetail', 'PeriodComparison', 'MasterRevenueSummary', 'ServiceRevenueSummary', 'RevenueReportResponse', 'ChatRequest', 'ChatResponse', 'FinancierRequest', 'FinancierResponse', 'ExpenseCreate', 'ExpenseUpdate', 'ExpenseOut', 'ExpenseCategoryItem', 'ExpenseCategoryBreakdown', 'ExpenseMonthPoint', 'ExpenseInsight', 'ExpenseAnalyticsResponse', 'ServiceMargin', 'PLReport', 'DiscountRuleCreate', 'DiscountRuleUpdate', 'DiscountRuleOut', 'ClientDiscountOut', 'DiscountAnalyticsTopRule', 'DiscountAnalyticsResponse', 'DiscountSuggestion', 'DiscountRuleAdvice', 'DiscountRoiItem', 'DiscountBeforeAfterPoint', 'DiscountIntelligenceResponse', 'ServiceDiscountRecOut', 'ServiceDiscountRecDecision', 'ServiceDiscountRecAnalyticsPoint', 'ServiceDiscountRecsResponse', 'LoyaltyPointsOut', 'LoyaltyPointsSummary', 'LoyaltyTierConfigOut', 'LoyaltyTierConfigUpdate', 'ClientTierOut', 'PhotoOut', 'PhotoOrderUpdate', 'PhotoCreateResponse', 'NotificationOut', 'UnreadCountOut', 'NotificationSettingsOut', 'NotificationSettingsUpdate', 'TelegramConnectRequest', 'PaymentCreateRequest', 'PaymentOut', 'PaymentWebhookRequest', 'MATERIAL_CATEGORIES', 'MATERIAL_UNITS', 'MaterialCreate', 'MaterialUpdate', 'MaterialOut', 'MaterialCategoryItem', 'MaterialMovementOut', 'StockHistoryPoint', 'AbcItemOut', 'CriticalItemOut', 'InventorySummaryOut', 'TechCardItemIn', 'TechCardItemOut', 'TechCardBlockIn', 'TechCardBlockOut', 'TechCardCreate', 'TechCardUpdate', 'TechCardOut', 'TechCardReorderIn', 'TechCardPhotoOut', 'PurchaseRecommendOut', 'AuditServiceBreakout', 'ConsumptionAuditOut', 'TechAnalyticsSummaryOut', 'AnomalyOut', 'AuditLogOut', 'AuditSyncResultOut']
